"""add pw hash

Revision ID: 874438bbaeda
Revises: 418fe3ed8966
Create Date: 2020-06-12 08:30:08.807093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874438bbaeda'
down_revision = '418fe3ed8966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
